name: manual-view-event

on:
  workflow_dispatch:

jobs:
  version:
    name: View github.event
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_SHA}"
      - run: echo "${GITHUB_REF}"
      - run: echo -e '${{toJSON(github)}}'
